// GENERATED by tools/probe_board_abi.py -- compile-only, never linked, never written into the tree.
#include <cstddef>
#include <cstdint>
#include "mr_features.h"
#include "node.h"
#include "device_nv.h"
#include "firmware_team_keyring.h"
#include "firmware_ui_model.h"
#include "firmware_ui_chrome.h"
#include "firmware_ui_invite.h"
#include "firmware_ui_presets.h"
struct MrAbiDivergenceFixture {
    void*    adapter_a;   // 8 B host / 4 B board
    uint8_t  pick;
    uint32_t gen;         // the incident's field: free on the host, paid for on the board
    void*    adapter_b;
};


namespace meshroute {
struct CandidateOpenCapture {
    uint8_t bytes[kRadminChunkSlots * kRadminChunkBytes];
    uint16_t len;
    uint16_t next_offset;
    uint16_t frame_cap;
    uint8_t phase;
    uint8_t truncated;
    uint8_t terminal;
    uint8_t next_seq;
};
struct CandidateOpenState {
    CandidateOpenCapture open[kRadminOpenSlots];
    uint16_t inbound_refusal;
    uint16_t open_rate_refusal;
};
struct CandidateRemoteSessionState {
    uint8_t     admin_x_secret[32];              // @0   — SECRET. The ADMINISTRATION root's X25519 scalar.
    uint8_t     admin_ed_pub[32];                // @32  — the administration root's Ed25519 public key.
                                                 //        ⛔ NEVER the messaging identity (`_ed_pub`): they are
                                                 //        separate secrets with separate lifetimes, and
                                                 //        `regen` rotates the messaging one alone.
    AdminAclRow acl[kRadminAclSlots];            // @64  — 340: the LIVE image the firmware installs
    uint8_t     readiness;                       // @404 — AdminReadiness
    uint8_t     acl_occupied;                    // @405 — validated occupied rows (0..10)
    uint8_t     root_present;                    // @406 — 1 iff a non-degenerate administration pair is installed
    uint8_t     reserved0;                       // @407 — canonical zero
    uint64_t    epoch[kRadminAclSlots];          // @408 — 80: the per-slot session epoch. 0 = slot UNUSABLE.
    SeenEntry   seen[kRadminSeenSlots];          // @488 — 896
    IngressOperationHeader ingress[kRadminIngressSlots];  // @1384 — 80
    IngressBodySlot        body[kRadminIngressSlots];     // @1464 — 472
    OpenStagingSlot        staging[kRadminStagingSlots];  // @1936 — 128
    TranscriptHeader      transcripts[kRadminTranscriptSlots];
    TranscriptChunk       chunks[kRadminChunkSlots];
    uint16_t              transcript_exhaustion;
    uint16_t              response_enqueue_failure;
    uint16_t              response_seal_failure;    CandidateOpenState slice7b2;
};
}
char mr_abi_size__meshroute_RemoteSessionState[sizeof(meshroute::RemoteSessionState)];
char mr_abi_align__meshroute_RemoteSessionState[alignof(meshroute::RemoteSessionState)];
#if MR_FEAT_RADMIN_ACCEPT
char mr_abi_included__meshroute_RemoteSessionState[1];
#endif
char mr_abi_size__meshroute_OpenStagingSlot[sizeof(meshroute::OpenStagingSlot)];
char mr_abi_align__meshroute_OpenStagingSlot[alignof(meshroute::OpenStagingSlot)];
#if MR_FEAT_RADMIN_ACCEPT
char mr_abi_included__meshroute_OpenStagingSlot[1];
#endif
char mr_abi_size__meshroute_CandidateOpenCapture[sizeof(meshroute::CandidateOpenCapture)];
char mr_abi_align__meshroute_CandidateOpenCapture[alignof(meshroute::CandidateOpenCapture)];
#if MR_FEAT_RADMIN_ACCEPT
char mr_abi_included__meshroute_CandidateOpenCapture[1];
#endif
char mr_abi_size__meshroute_CandidateOpenState[sizeof(meshroute::CandidateOpenState)];
char mr_abi_align__meshroute_CandidateOpenState[alignof(meshroute::CandidateOpenState)];
#if MR_FEAT_RADMIN_ACCEPT
char mr_abi_included__meshroute_CandidateOpenState[1];
#endif
char mr_abi_size__meshroute_CandidateRemoteSessionState[sizeof(meshroute::CandidateRemoteSessionState)];
char mr_abi_align__meshroute_CandidateRemoteSessionState[alignof(meshroute::CandidateRemoteSessionState)];
#if MR_FEAT_RADMIN_ACCEPT
char mr_abi_included__meshroute_CandidateRemoteSessionState[1];
#endif
char mr_abi_size__meshroute_Node[sizeof(meshroute::Node)];
char mr_abi_align__meshroute_Node[alignof(meshroute::Node)];
char mr_abi_included__meshroute_Node[1];
char mr_abi_size__MrAbiDivergenceFixture[sizeof(MrAbiDivergenceFixture)];
char mr_abi_align__MrAbiDivergenceFixture[alignof(MrAbiDivergenceFixture)];
char mr_abi_included__MrAbiDivergenceFixture[1];
