from pathlib import Path
import json,re
R=Path('/home/staszek/MeshRoute');E=R/'docs/superpowers/evidence/2026-10-02-b478-b487-b488-qa-regate';P=R/'docs/2026-07-30-open-bug-register.md';s=P.read_text()
start=s.index('**Tool package B478 + B487 + B488, with B490, B491 and B492 —');end=s.index('\n\n',start)
s=s[:start]+'''**Tool package B478 + B487 + B488, with B490, B491 and B492 — INDEPENDENT QA PASS 2026-10-02.** [Fresh return gate](superpowers/evidence/2026-10-02-b478-b487-b488-qa-regate.md) reran A10's four proofs and the entire revision-4 §4.2 chain on the frozen candidate above owner commit `4c1a000` (parent `10f3332`); all 136 committed paths match the approved tree. Part A **24**, Part B **24**, discovery **447 OK / no skips**; stock transcripts **202/206**, fresh pairs and all ten reference rows identical; inventory **197**; census **109/1963/62**, only F07's replacement changed. Both battery modes are **9/9 RED**, counts **39/169/36/4/4/25/13/6/23**; worker baselines **3059/199638/0**. Bounded F07 has zero overruns in **106722** calls (old F07: **992**) and the same **13** failing sites on **456/456** replays. **B478/B487/B488/B490/B491/B492 CLOSED** in place. Separate pre-existing **B496** records unclosed test streams; B479–B481/B489/B493–B495 remain excluded and open. Approved brief, preparation inputs and historical/coder evidence stayed unchanged throughout the gate; QA landing changes documentation only. **Next: W7 QA pre-check, then the author's brief and its QA review; no W7 code authorized.** Commits do not block progress.'''+s[end:]
notes={
478:'The full byte/exit/retention regressions pass through real children and both orchestrator modes; all 11 defect cases fail before for their own reason and pass after, all seven new controls and both prior self-test controls discriminate, and the three integrity faults preserve exits 9/9/2.',
487:'Fresh stock builds use the real inbox runner prefix and validate five macros on both profiles: 202 full_headless and 206 mobile rows; each fresh pair compares 0 and all ten pinned reference rows agree.',
488:'The array-reference adapter preserves the source-derived 1023-byte admitted limit; the new boundary records pass and B-C1 restores the pointer defect, refusing all 164 rows over seven bytes and differing on its pinned records.',
490:'Credited verdicts require the agreeing 0/1 exit and both summaries; real summary-then-signal and unexpected-exit cases remain UNUSABLE with raw streams retained. Removing agreement makes the named regressions fail.',
491:'Only parse_ledger changed from the first QA freeze; verify_profile and exception handlers are unchanged. All 24 Part B tests pass; three malformed cases refuse with 2 and no traceback in both CLI positions, and the malformed fresh-driver profile is refused by name.',
492:'The one bounded F07 replacement and comment preserve all other tuples. Clean/new sweeps have zero overruns in 106722 calls per arm; the old arm exposes 992. Both worker modes give meaningful RED at 13 assertions, and all 456 replays share the same 13-site set, including the roomy-capacity lengths check. The old 42/44 count is retired.'}
labels={478:'TOOL BYTE CAPTURE',487:'TOOL BUILD/PROFILE',488:'TOOL ADAPTER FIDELITY',490:'TOOL VERDICT',491:'TOOL VALIDATION',492:'MUTATION INSTRUMENT'}
for n in notes:
 pattern=r'^\| B'+str(n)+r' \| .*? \| (.*) \|$';m=re.search(pattern,s,re.M);assert m,n
 body=m.group(1)+' **CLOSED 2026-10-02:** '+notes[n]+' [Independent return gate](superpowers/evidence/2026-10-02-b478-b487-b488-qa-regate.md).'
 s=s[:m.start()]+'| B'+str(n)+' | **CLOSED / '+labels[n]+' — independent QA PASS 2026-10-02** | '+body+' |'+s[m.end():]
assert '| B496 |' not in s
row='''| B496 | **OPEN / MINOR TEST STREAM HYGIENE — independent tool-package return QA 2026-10-02; pre-existing, outside the package** | `tools/test_compare_corpus_slice_s1b.py:375` and the standalone worker-formula ledger at `tools/test_worker_formula_derived.py:144` give `unittest.TextTestRunner` an `open("/dev/null", "w")` stream without explicitly closing it. Full discovery emits `ResourceWarning: unclosed file`; the same warning is in the original QA and coder discovery logs. Independent warning-enabled runs with allocation tracing identify both sites, each **exit 0**; both source files are byte-identical to `10f3332`. No assertion/verdict is lost; this is a non-blocking test hygiene finding, not B478/B491/B492. **CLOSE BY:** separately fence explicit stream lifetime (for example a context manager), rerun the vacuity control and worker-formula ledger without their warning, preserve their failure/exit contracts, and run full tools discovery. [QA measurements](superpowers/evidence/2026-10-02-b478-b487-b488-qa-regate.md#separate-finding-and-scope-limits). |'''
m=re.search(r'^\| B495 \|.*$',s,re.M);assert m;s=s[:m.end()]+'\n'+row+s[m.end():]
assert s.count('The next free finding is **B496**')==1;s=s.replace('The next free finding is **B496** (','The next free finding is **B497** (B496 registered by independent return QA, 2026-10-02: pre-existing unclosed diagnostic test streams; ');P.write_text(s)
receipt='docs/superpowers/evidence/2026-10-02-b478-b487-b488-qa-regate.md'
for path in ['tracker.md','MEMORY.md']:
 p=R/path;s=p.read_text();start=s.index('current: W0 —');end=s.index(' W0 physical persistence',start)
 s=s[:start]+f'current: the owner-ruled B478/B487/B488 tool package, with B490/B491/B492 — [independent QA PASS 2026-10-02]({receipt}); next: W7 QA pre-check, then the author\'s brief and QA review. B496 is a separate pre-existing test-stream warning.'+s[end:];p.write_text(s)
p=R/'docs/superpowers/specs/2026-09-06-standalone-mobile-home-and-team-messaging-design.md';s=p.read_text();m=re.search(r'^\| W7 \|.*$',s,re.M);assert m
row=m.group(0);assert row.endswith(' |');row=row[:-2]+''' **Status 2026-10-02: READY FOR QA PRE-CHECK**, then the author's brief and QA review. W0/W4b/W6 are QA-passed, and the owner-ruled B478/B487/B488 tool prerequisite (with B490/B491/B492) is [independent QA PASS](../evidence/2026-10-02-b478-b487-b488-qa-regate.md). No W7 implementation authorized; commits are not progress gates. |''';s=s[:m.start()]+row+s[m.end():];p.write_text(s)
(E/'landing-notes.json').write_text(json.dumps({'closed_findings':list(notes),'new_finding':496,'next_free':497,'dispatch':'W7 QA pre-check -> author brief -> QA brief review','metal_change':False,'product_change':False,'status_documents':['docs/2026-07-30-open-bug-register.md','tracker.md','MEMORY.md','docs/superpowers/specs/2026-09-06-standalone-mobile-home-and-team-messaging-design.md']},indent=2)+'\n')
print('Landed six closures, B496, W7 pointers; no tool/product/brief edits')
