from pathlib import Path
import hashlib,json,re,subprocess
R=Path('/home/staszek/MeshRoute');O=R/'artifacts/2026-10-02-b478-b487-b488-qa-regate'
patterns=[r'probe_ui_model_mutations|SuiteFailure|retain_shipped|ship_streams|unusable_verdict|run_suite\(',r'transcript\.py|transcript_main\.cpp|MR0C-PROFILE|parse_ledger|validate_ledger',r'ui_fmt_identity\(|label_from_hash\(|label_for_team_id\(|label_for_origin\(']
records=[]
for i,p in enumerate(patterns):
 x=subprocess.run(['rg','-n',p,'lib','src','test','tools','-g','*.py','-g','*.sh','-g','*.cpp','-g','*.h'],cwd=R,capture_output=True);assert x.returncode in (0,1);(O/('readers-'+str(i)+'.txt')).write_bytes(x.stdout);records.append({'pattern':p,'files':sorted(set(line.split(':',1)[0] for line in x.stdout.decode().splitlines()))})
checks={'tools/test_mutation_unusable_reason.py':'AST extracts real capture/retention functions; 24 regressions and explicit controls rerun','tools/test_worker_formula_derived.py':'strict worker constants and prose patterns are unchanged; discovery rerun','tools/test_probe_inbox_transcript.py':'new ledger/output/builder tests and B491 refusals; 24 cases rerun','tools/probe_inbox_verbs/run.sh':'builder prefix unchanged and copied verbatim by each fresh transcript build','tools/probe_inbox_verbs/probe_main.cpp':'adapter stand-in unchanged; transcript live-name setup verified in the new driver','tools/probe_deferred_actions/run.py':'same untouched inbox builder and included fixture; no transcript-output predicate','tools/probe_firmware_ui/run.sh':'label trampoline and source-control anchors unchanged; does not read F07 replacement table','tools/probe_firmware_ui/probe_main.cpp':'trampoline destination15 and passed width14; no new active roomy caller','tools/probe_board_abi.py':'historical harness references only; product/layout files identical','tools/probe_console_sink/ownership.py':'historical harness/reader references; no altered predicate','tools/probe_features/run.sh':'historical test instructions; ownership inputs unchanged','tools/probe_ble_line/run.sh':'historical battery instructions; runtime inputs unchanged','tools/probe_custody_usb/run.sh':'historical mutation reference; runtime inputs unchanged','tools/probe_board_ui/run.sh':'battery mentions only; product and probe inputs unchanged'}
for p in checks:assert (R/p).is_file()
extra={'historical_source_and_test_comments':'references do not consume changed harness/table text; all product and native-test input bytes unchanged','evidence_scripts':'historical copies/readers pinned and never edited; current QA recipes name the one allowed F07 exception','mutation_consumers':'all109 lists, target/pin/worker AST unchanged except exact F07 replacement; census and both required workers verified','external_output':'no lib/src/test consumer of transcript CLI output; current real consumer is tools/test_probe_inbox_transcript.py'}
result={'verdict':'PASS','grep_groups':records,'reader_dispositions':checks,'other_dispositions':extra,'A10_callers':'callers.json includes complete src/test census and probe-only wrapper separately'}
(O/'reader-audit.json').write_text(json.dumps(result,indent=2)+'\n');print('PASS reader audit',len(set(f for g in records for f in g['files'])),'files matched; all affected regression/AST readers gated')
