#!/bin/bash
S=/tmp/claude-1001/-home-staszek-MeshRoute/29a5e6f2-869e-46c1-aa18-9fb7b0d23189/scratchpad/s8bgate; W=/home/staszek/MeshRoute; LUS=/home/staszek/lora-universal-simulator/build/orchestrator/lus
REF=/home/staszek/mr-slice2-ref/bin/python; PROOF=docs/superpowers/evidence/2026-09-13-radmin-slice7b3-0-precheck/result-domain-proof.cpp
cd $W
echo "== BASE"; git rev-parse HEAD; git status --short | wc -l; git -C /home/staszek/lora-universal-simulator rev-parse HEAD; git -C /home/staszek/lora-universal-simulator status --short; sha256sum lib/core/remote_client.h lib/core/remote_client.cpp lib/core/node.h lib/core/node.cpp lib/core/node_mac.cpp lib/core/node_mac_rx.cpp lib/core/node_hashlocate.cpp src/firmware_remote_client.h src/firmware_remote_client.cpp src/firmware_commands.cpp src/fw_main.cpp src/device_rng.h src/device_ble.h src/firmware_command_authority.h platformio.ini | cut -c1-16,65-
echo "== NATIVE"; pio test -e native > $S/native_pio.log 2>&1; echo "pio rc=${PIPESTATUS[0]}"; ./.pio/build/native/program > $S/native_prog.log 2>&1; echo "prog rc=$?"; grep -E "test cases|assertions" $S/native_prog.log
echo "== REFERENCE (extended, strict 94 + old-89 identity + selftest)"; $REF docs/superpowers/evidence/2026-09-13-radmin-slice7b3-0-reference.py --freeze-check --compare test/test_remote_codec.cpp --selftest > $S/reference.log 2>&1; echo "rc=$?"; grep -E "Strict|identity|OK:|CONTROL|MISMATCH|freeze|89|94" $S/reference.log | tail -12
echo "== LUS before"; md5sum $LUS; cmake --build /home/staszek/lora-universal-simulator/build -j8 > $S/lus_build.log 2>&1; echo "cmake rc=$?"; grep -cE "Building|Linking" $S/lus_build.log; grep -cE "remote_client|node_mac_rx|node_mac\.cpp|node\.cpp" $S/lus_build.log; echo "== LUS after"; md5sum $LUS
echo "== CORPUS"; python3 tools/run_corpus.py --jobs=8 --require-anchors --out $S/corpus --lus $LUS > $S/corpus.log 2>&1; echo "corpus rc=$?"; grep -E "PASS|FAIL|anchors|s18_meshroute" $S/corpus.log | head -5; grep -l "radmin" $S/corpus/streams/*.ndjson 2>/dev/null | wc -l
echo "== ABI"; python3 tools/probe_board_abi.py > $S/abi.log 2>&1; echo "rc=$?"; grep -E "meshroute::Node  |^PASS|^FAIL" $S/abi.log | head -4
echo "== ROW ABI"; python3 tools/probe_b278_row_abi.py > $S/rowabi.log 2>&1; echo "rc=$?"; grep -E "^PASS|^FAIL" $S/rowabi.log | tail -1
for p in console_sink inbox_verbs firmware_ui custody_usb ble_line features; do echo "== PROBE $p"; tools/probe_$p/run.sh > $S/probe_$p.log 2>&1; echo "rc=$?"; grep -E "^PASS|^FAIL|PASS:|FAIL:|PINS|controls:|checks:|probe:|matrix:|ownership controls|ADMIN|CLIENT-GUARD|arm" $S/probe_$p.log | tail -8; echo "== PROBE $p --no-neg"; tools/probe_$p/run.sh --no-neg > $S/probe_${p}_noneg.log 2>&1; echo "rc=$?"; tail -2 $S/probe_${p}_noneg.log; done
echo "== PROBE deferred_actions"; tools/probe_deferred_actions/run.sh > $S/probe_deferred_actions.log 2>&1; echo "rc=$?"; grep -E "^PASS|^FAIL|PASS:|FAIL:|PINS|controls|checks|reader" $S/probe_deferred_actions.log | tail -6; echo "== PROBE deferred_actions --no-neg"; tools/probe_deferred_actions/run.sh --no-neg > $S/probe_deferred_actions_noneg.log 2>&1; echo "rc=$?"; tail -2 $S/probe_deferred_actions_noneg.log
echo "== PROBE inbox_verbs CLIENT arm"; MR_PROBE_ARM=client tools/probe_inbox_verbs/run.sh > $S/probe_inbox_verbs_client.log 2>&1; echo "rc=$?"; grep -E "^PASS|^FAIL|PASS:|FAIL:|PINS|controls:|checks:|arm" $S/probe_inbox_verbs_client.log | tail -6
echo "== UNITTEST"; python3 -m unittest discover -s tools -p "test_*.py" > $S/unittest.log 2>&1; echo "rc=$?"; grep -E "^Ran|^OK$|^FAILED|skipped" $S/unittest.log
echo "== INVENTORY"; python3 tools/gen_command_inventory.py --write > $S/inv_write.log 2>&1; echo "write rc=$?"; git diff --stat -- docs/superpowers/evidence/2026-09-04-radmin-command-inventory.md | tail -1; python3 tools/gen_command_inventory.py > $S/inv.log 2>&1; echo "bare rc=$?"; tail -1 $S/inv.log; python3 tools/gen_command_inventory.py --check > $S/inv_check.log 2>&1; echo "check rc=$?"; tail -1 $S/inv_check.log
echo "== AUTHORITY"; python3 tools/check_command_authority.py > $S/authority.log 2>&1; echo "rc=$?"; tail -2 $S/authority.log; python3 tools/check_command_authority.py --selftest > $S/authority_selftest.log 2>&1; echo "selftest rc=$?"; grep -cE "RED|red" $S/authority_selftest.log; tail -2 $S/authority_selftest.log
echo "== A0"; python3 tools/check_a0_matrix.py > $S/a0.log 2>&1; echo "rc=$?"; echo "== DTL"; python3 tools/check_data_type_literals.py > $S/dtl.log 2>&1; echo "rc=$?"; tail -1 $S/dtl.log
echo "== DIFF CHECK"; git diff --check; echo "mr rc=$?"; git -C /home/staszek/lora-universal-simulator diff --check; echo "sim rc=$?"
echo "== CENSUS"; tools/warning_census.sh > $S/census.log 2>&1; echo "rc=$?"; grep -E "^(gateway|heltec|xiao)|^PASS|^FAIL|Wswitch" $S/census.log
echo "== BOARD PAIR"; python3 tools/measure_board.py pair --output .pio-measure/qa-s8b-final --jobs=2 > $S/board.log 2>&1; echo "rc=$?"; grep -h "RAM=" $S/board.log; for e in gateway heltec_mobile; do echo "$e elf=$(sha256sum .pio-measure/qa-s8b-final/$e/firmware.elf | cut -c1-16)"; done
echo "== XIAO one-off"; pio run -e xiao_mobile > $S/xiao.log 2>&1; echo "rc=$?"; grep -E "^RAM:|^Flash:" $S/xiao.log | sed "s/  */ /g"
touch $S/chain.done
