// GENERATED by tools/probe_board_abi.py -- compile-only, never linked, never written into the tree.
#include <cstddef>
#include <cstdint>
#include "firmware_join_service.h"
#include "mr_features.h"
#include "node.h"
#include "device_nv.h"
#include "firmware_team_keyring.h"
#include "firmware_ui_model.h"
#include "firmware_ui_chrome.h"
#include "firmware_ui_invite.h"
#include "firmware_ui_presets.h"
// AUTHOR PRICING CANDIDATE ONLY. Not a production plan or storage authorization.
#include "console_line.h"
namespace meshroute {
struct HistoricalDeferredCandidate {
    uint64_t request_id;
    uint32_t activate_at_ms;
    uint8_t action, controller_slot, armed, ack_seen, in_use;
};
struct CandidateDeferredAction {
    uint64_t request_id, admin_epoch, activate_at_ms;
    uint32_t source_hash, activation_ms;
    uint16_t command_len;
    uint8_t controller_slot, authority, action, phase;
    uint8_t reserved[2];
    uint8_t command[console::remote_command_max_bytes + 1];
};
struct CandidateTranscriptHeader {
    uint64_t request_id;
    uint32_t bytes_total;          // retained bytes, not attempted writes after truncation
    uint16_t first_chunk;
    uint8_t frames;                // OUTPUT chunks + mandatory TERMINAL
    uint8_t next_seq_to_send;
    uint8_t controller_slot;
    uint8_t seen_index;
    uint8_t terminal;
    uint8_t state;
    uint16_t chunk_bytes;          // computed once at reservation for the actual return carrier
    uint8_t truncated;
    uint8_t order;                // 0..3 allocation order; no uptime-wrap-dependent scheduling
    uint32_t activation_ms;
};
struct CandidateRemoteSessionState {
    uint8_t     admin_x_secret[32];              // @0   — SECRET. The ADMINISTRATION root's X25519 scalar.
    uint8_t     admin_ed_pub[32];                // @32  — the administration root's Ed25519 public key.
                                                 //        ⛔ NEVER the messaging identity (`_ed_pub`): they are
                                                 //        separate secrets with separate lifetimes, and
                                                 //        `regen` rotates the messaging one alone.
    AdminAclRow acl[kRadminAclSlots];            // @64  — 340: the LIVE image the firmware installs
    uint8_t     readiness;                       // @404 — AdminReadiness
    uint8_t     acl_occupied;                    // @405 — validated occupied rows (0..10)
    uint8_t     root_present;                    // @406 — 1 iff a non-degenerate administration pair is installed
    uint8_t     reserved0;                       // @407 — canonical zero
    uint64_t    epoch[kRadminAclSlots];          // @408 — 80: the per-slot session epoch. 0 = slot UNUSABLE.
    SeenEntry   seen[kRadminSeenSlots];          // @488 — 896
    IngressOperationHeader ingress[kRadminIngressSlots];  // @1384 — 80
    IngressBodySlot        body[kRadminIngressSlots];     // @1464 — 472
    OpenStagingSlot        staging[kRadminStagingSlots];  // @1936 — 128
    CandidateTranscriptHeader      transcripts[kRadminTranscriptSlots];
    TranscriptChunk       chunks[kRadminChunkSlots];
    uint16_t              transcript_exhaustion;
    uint16_t              response_enqueue_failure;
    uint16_t              response_seal_failure;
    OpenCapture           open[kRadminOpenSlots];
    uint16_t              inbound_refusal;
    uint16_t              open_rate_refusal;
    CandidateDeferredAction actions[1];
};
}
struct MrAbiDivergenceFixture {
    void*    adapter_a;   // 8 B host / 4 B board
    uint8_t  pick;
    uint32_t gen;         // the incident's field: free on the host, paid for on the board
    void*    adapter_b;
};
char mr_abi_size__meshroute_HistoricalDeferredCandidate[sizeof(meshroute::HistoricalDeferredCandidate)];
char mr_abi_align__meshroute_HistoricalDeferredCandidate[alignof(meshroute::HistoricalDeferredCandidate)];
#if MR_FEAT_RADMIN_ACCEPT
char mr_abi_included__meshroute_HistoricalDeferredCandidate[1];
#endif
char mr_abi_size__meshroute_CandidateDeferredAction[sizeof(meshroute::CandidateDeferredAction)];
char mr_abi_align__meshroute_CandidateDeferredAction[alignof(meshroute::CandidateDeferredAction)];
#if MR_FEAT_RADMIN_ACCEPT
char mr_abi_included__meshroute_CandidateDeferredAction[1];
#endif
char mr_abi_size__meshroute_TranscriptHeader[sizeof(meshroute::TranscriptHeader)];
char mr_abi_align__meshroute_TranscriptHeader[alignof(meshroute::TranscriptHeader)];
#if MR_FEAT_RADMIN_ACCEPT
char mr_abi_included__meshroute_TranscriptHeader[1];
#endif
char mr_abi_size__meshroute_CandidateTranscriptHeader[sizeof(meshroute::CandidateTranscriptHeader)];
char mr_abi_align__meshroute_CandidateTranscriptHeader[alignof(meshroute::CandidateTranscriptHeader)];
#if MR_FEAT_RADMIN_ACCEPT
char mr_abi_included__meshroute_CandidateTranscriptHeader[1];
#endif
char mr_abi_size__meshroute_RemoteSessionState[sizeof(meshroute::RemoteSessionState)];
char mr_abi_align__meshroute_RemoteSessionState[alignof(meshroute::RemoteSessionState)];
#if MR_FEAT_RADMIN_ACCEPT
char mr_abi_included__meshroute_RemoteSessionState[1];
#endif
char mr_abi_size__meshroute_CandidateRemoteSessionState[sizeof(meshroute::CandidateRemoteSessionState)];
char mr_abi_align__meshroute_CandidateRemoteSessionState[alignof(meshroute::CandidateRemoteSessionState)];
#if MR_FEAT_RADMIN_ACCEPT
char mr_abi_included__meshroute_CandidateRemoteSessionState[1];
#endif
char mr_abi_size__meshroute_Node[sizeof(meshroute::Node)];
char mr_abi_align__meshroute_Node[alignof(meshroute::Node)];
#if MR_FEAT_RADMIN_ACCEPT
char mr_abi_included__meshroute_Node[1];
#endif
char mr_abi_size__MrAbiDivergenceFixture[sizeof(MrAbiDivergenceFixture)];
char mr_abi_align__MrAbiDivergenceFixture[alignof(MrAbiDivergenceFixture)];
char mr_abi_included__MrAbiDivergenceFixture[1];

char mr_abi_size__mrfw_JoinRequest[sizeof(mrfw::JoinRequest)];
char mr_abi_align__mrfw_JoinRequest[alignof(mrfw::JoinRequest)];
