#!/bin/bash
S=/tmp/claude-1001/-home-staszek-MeshRoute/29a5e6f2-869e-46c1-aa18-9fb7b0d23189/scratchpad/s10gate; W=/home/staszek/MeshRoute; LUS=/home/staszek/lora-universal-simulator/build/orchestrator/lus
REF=/home/staszek/mr-slice2-ref/bin/python
cd $W
echo "== BASE $(date +%H:%M:%S)"; git rev-parse HEAD; git status --short | wc -l; git -C /home/staszek/lora-universal-simulator rev-parse HEAD; git -C /home/staszek/lora-universal-simulator status --short; sha256sum src/device_nv.h src/firmware_config.h src/fw_main.cpp lib/core/node.h test/test_custody_receive_g.cpp test/test_device_nv.cpp test/test_firmware_config_service.cpp test/test_firmware_provisioning_service.cpp tools/probe_board_abi.py tools/probe_console_sink/negctl.py tools/probe_console_sink/run.sh tools/probe_console_sink/structural.py tools/probe_features/ownership.py tools/probe_inbox_verbs/probe_main.cpp tools/probe_inbox_verbs/run.sh src/firmware_config.cpp platformio.ini tools/probe_ui_model_mutations.py | cut -c1-16,65-
echo "== LAYOUT (native, real frozen headers)"; g++ -std=gnu++2a -DMESHROUTE_NATIVE=1 -DMR_N_LAYERS=2 -I lib/core -I lib/hal -I src -g -O0 -o $S/measure $S/measure.cpp > $S/measure.log 2>&1; echo "g++ rc=$?"; $S/measure
echo "== CENSUS-OF-GUARDS"; echo "node.h #if MR_FEAT_RADMIN lines: $(grep -c '^#if MR_FEAT_RADMIN' lib/core/node.h)"; python3 -c "
import ast,re
src=open('tools/probe_features/ownership.py').read(); m=re.search(r'APPROVED_SITES = (\{.*?\n\})', src, re.S); d=ast.literal_eval(m.group(1)); l=d['lib/core/node.h']; print('ownership node.h sites', len(l), 'ACCEPT-only', sum(1 for x in l if x=='#if MR_FEAT_RADMIN_ACCEPT'), 'CLIENT-only', sum(1 for x in l if x=='#if MR_FEAT_RADMIN_CLIENT'), 'shared', sum(1 for x in l if '||' in x))"
echo "== NATIVE $(date +%H:%M:%S)"; pio test -e native > $S/native_pio.log 2>&1; echo "pio rc=${PIPESTATUS[0]}"; ./.pio/build/native/program > $S/native_prog.log 2>&1; echo "prog rc=$?"; grep -E "test cases|assertions" $S/native_prog.log
echo "== REFERENCE (extended)"; $REF docs/superpowers/evidence/2026-09-13-radmin-slice7b3-0-reference.py --freeze-check --compare test/test_remote_codec.cpp --selftest > $S/reference.log 2>&1; echo "rc=$?"; grep -E "Strict|identity|OK:|CONTROL|MISMATCH|freeze|89|94" $S/reference.log | tail -8
echo "== REFERENCE slice9"; $REF docs/superpowers/evidence/2026-09-19-radmin-slice9-reference.py --freeze-check --compare test/test_remote_codec.cpp --selftest > $S/reference9.log 2>&1; echo "rc=$?"; tail -4 $S/reference9.log
echo "== LUS before"; md5sum $LUS; cmake --build /home/staszek/lora-universal-simulator/build -j8 > $S/lus_build.log 2>&1; echo "cmake rc=$?"; grep -cE "Building|Linking" $S/lus_build.log; echo "== LUS after"; md5sum $LUS
echo "== CORPUS $(date +%H:%M:%S)"; python3 tools/run_corpus.py --jobs=8 --require-anchors --out $S/corpus --lus $LUS > $S/corpus.log 2>&1; echo "corpus rc=$?"; grep -E "PASS|FAIL|anchors|s18_meshroute" $S/corpus.log | head -5
echo "== ABI"; python3 tools/probe_board_abi.py > $S/abi.log 2>&1; echo "rc=$?"; grep -E "meshroute::Node  |^PASS|^FAIL" $S/abi.log | head -4
echo "== ROW ABI"; python3 tools/probe_b278_row_abi.py > $S/rowabi.log 2>&1; echo "rc=$?"; grep -E "^PASS|^FAIL" $S/rowabi.log | tail -1
for p in console_sink inbox_verbs firmware_ui custody_usb ble_line features; do echo "== PROBE $p $(date +%H:%M:%S)"; tools/probe_$p/run.sh > $S/probe_$p.log 2>&1; echo "rc=$?"; grep -E "^PASS|^FAIL|PASS:|FAIL:|PINS|controls:|checks:|probe:|matrix:|ownership controls|arm" $S/probe_$p.log | tail -6; echo "== PROBE $p --no-neg"; tools/probe_$p/run.sh --no-neg > $S/probe_${p}_noneg.log 2>&1; echo "rc=$?"; tail -2 $S/probe_${p}_noneg.log; done
echo "== PROBE deferred_actions"; tools/probe_deferred_actions/run.sh > $S/probe_deferred_actions.log 2>&1; echo "rc=$?"; grep -E "^PASS|^FAIL|PASS:|FAIL:|PINS|controls|checks|reader" $S/probe_deferred_actions.log | tail -6; echo "== PROBE deferred_actions --no-neg"; tools/probe_deferred_actions/run.sh --no-neg > $S/probe_deferred_actions_noneg.log 2>&1; echo "rc=$?"; tail -2 $S/probe_deferred_actions_noneg.log
echo "== PROBE inbox_verbs CLIENT arm"; MR_PROBE_ARM=client tools/probe_inbox_verbs/run.sh > $S/probe_inbox_verbs_client.log 2>&1; echo "rc=$?"; grep -E "^PASS|^FAIL|PASS:|FAIL:|PINS|controls:|checks:|arm" $S/probe_inbox_verbs_client.log | tail -6
echo "== BOARD-UI supplemental (expect exactly W49/W51/W54, B418)"; tools/probe_board_ui/run.sh --no-neg > $S/probe_board_ui_noneg.log 2>&1; echo "rc=$?"; grep -E "FAIL W|wiring:|structural:" $S/probe_board_ui_noneg.log | cut -c1-110 | tail -5
echo "== ABSENCE slice-10 symbols"; grep -rnE "admin_load|admin_pubkey|admin_counter_floor|admin_provisioned|_admin_pubkey|_admin_counter_floor|_admin_provisioned" lib src test tools --include=*.h --include=*.cpp --include=*.py --include=*.sh --include=*.ini > $S/absence10_raw.txt 2>/dev/null; grep -vE ":[0-9]+:\s*(//|#|\*|/\*)" $S/absence10_raw.txt > $S/absence10_noncomment.txt; echo "raw=$(wc -l < $S/absence10_raw.txt) noncomment=$(wc -l < $S/absence10_noncomment.txt)"; cut -c1-150 $S/absence10_noncomment.txt
echo "== ABSENCE slice-9 regression"; grep -rnE "send_remote_cmd|send_remote_response|\bremote_exec\b|handle_rcmd|handle_unlock|handle_lock|handle_password|admin_cmd_seal|admin_cmd_open|admin_key_from_password|REMOTE_FLAG_SEALED|MR_FEAT_REMOTE_MGMT|console_binary|bin::enc_|g_admin_id|g_admin_unlocked|g_admin_tx_ctr|firmware_remote\.h|admin_auth\.h|admin_set_pubkey|admin_counter_check_advance" lib src test tools --include=*.h --include=*.cpp --include=*.py --include=*.sh --include=*.ini > $S/absence9_raw.txt 2>/dev/null; grep -vE ":[0-9]+:\s*(//|#|\*|/\*)" $S/absence9_raw.txt > $S/absence9_noncomment.txt; echo "raw=$(wc -l < $S/absence9_raw.txt) noncomment=$(wc -l < $S/absence9_noncomment.txt)"; cut -d: -f1 $S/absence9_noncomment.txt | sort | uniq -c | sort -rn | head -8
echo "== INVENTORY check-first (B433)"; python3 tools/gen_command_inventory.py --check > $S/inv_check.log 2>&1; echo "check rc=$?"; tail -1 $S/inv_check.log
echo "== UNITTEST $(date +%H:%M:%S)"; python3 -m unittest discover -s tools -p "test_*.py" > $S/unittest.log 2>&1; echo "rc=$?"; grep -E "^Ran|^OK$|^FAILED|skipped" $S/unittest.log
echo "== INVENTORY write/bare"; python3 tools/gen_command_inventory.py --write > $S/inv_write.log 2>&1; echo "write rc=$?"; git diff --stat -- docs/superpowers/evidence/2026-09-04-radmin-command-inventory.md | tail -1; python3 tools/gen_command_inventory.py > $S/inv.log 2>&1; echo "bare rc=$?"; tail -1 $S/inv.log
echo "== AUTHORITY"; python3 tools/check_command_authority.py > $S/authority.log 2>&1; echo "rc=$?"; tail -2 $S/authority.log; python3 tools/check_command_authority.py --selftest > $S/authority_selftest.log 2>&1; echo "selftest rc=$?"; tail -1 $S/authority_selftest.log
echo "== A0"; python3 tools/check_a0_matrix.py > $S/a0.log 2>&1; echo "rc=$?"; echo "== DTL"; python3 tools/check_data_type_literals.py > $S/dtl.log 2>&1; echo "rc=$?"; tail -1 $S/dtl.log
echo "== DIFF CHECK"; git diff --check; echo "mr rc=$?"; git -C /home/staszek/lora-universal-simulator diff --check; echo "sim rc=$?"
echo "== PART 57f"; grep -c "57f" docs/2026-07-31-bench-test-script.md
echo "== CENSUS $(date +%H:%M:%S)"; tools/warning_census.sh > $S/census.log 2>&1; echo "rc=$?"; grep -E "^(gateway|heltec|xiao)|^PASS|^FAIL|Wswitch" $S/census.log
echo "== BOARD PAIR $(date +%H:%M:%S)"; python3 tools/measure_board.py pair --output .pio-measure/qa-s10-final --jobs=2 > $S/board.log 2>&1; echo "rc=$?"; grep -h "RAM=" $S/board.log; for e in gateway heltec_mobile; do echo "$e elf=$(sha256sum .pio-measure/qa-s10-final/$e/firmware.elf | cut -c1-16)"; done
echo "== XIAO one-off"; pio run -e xiao_mobile > $S/xiao.log 2>&1; echo "rc=$?"; grep -E "^RAM:|^Flash:" $S/xiao.log | sed "s/  */ /g"
echo "== END $(date +%H:%M:%S)"; touch $S/chain.done
