"""One-source controls; each must compile and fail the executed action assertions."""
CONTROLS = [
 ('C01 second inbox wipe skipped','src/firmware_commands.cpp',
  'const bool dm_ok = g_inbox_dm.wipe(), ch_ok = g_inbox_ch.wipe();',
  'const bool dm_ok = g_inbox_dm.wipe(), ch_ok = true;',2,1),
 ('C02 NV erase skipped','src/firmware_commands.cpp',
  'const bool nv_ok = mrnv::factory_erase();','const bool nv_ok = true;',2,1),
 ('C03 inbox warning suppressed','src/firmware_commands.cpp',
  'if (!dm_ok || !ch_ok) out.println(F("> factory_reset WARN: inbox erase incomplete (messages may remain on flash)"));',
  'if (false) out.println(F("> factory_reset WARN: inbox erase incomplete (messages may remain on flash)"));',2,1),
 ('C04 local confirmation bypassed','src/firmware_commands.cpp',
  'if (admission.status != ActionAdmissionStatus::confirmation) {','if (true) {',2,1),
 ('C05 sleep selection ignored','src/firmware_commands.cpp',
  'action_sleep_apply(admission.plan.kind, out);','action_sleep_apply(ActionKind::sleep_on, out);',2,1),
 ('C06 factory reset sink escapes','src/firmware_commands.cpp',
  'return action_reboot_apply(backend, reboot_out, observer, reset_outcome);',
  'return action_reboot_apply(backend, mrcon, observer, reset_outcome);',2,1),
 ('C07 reset mark missing','src/fw_main.cpp',
  'mrfault::mark_expected_reset();   // v2 fault log: classify the upcoming reset as REBOOT, not UNEXPECTED',
  '// missing expected-reset mark',1,1),
 ('C08 prep does not halt','src/fw_main.cpp',
  'g_halted = true;                              // the loop now skips the operating block',
  'g_halted = false;                             // the loop now skips the operating block',2,1),
 ('C09 apply repeats mutable debug admission','src/fw_main.cpp',
  '    if (plan.kind == ActionKind::crash_hang) {',
  '    if (!meshroute::g_mr_trace_on) return action_report(observer, ActionOutcome::backend_failed);\n    if (plan.kind == ActionKind::crash_hang) {',2,1),
 ('C10 remote entry toggles active OTA off','src/fw_main.cpp',
  '    if (mrota::ota_start(out)) {',
  '    if (mrota::ota_active()) { mrota::ota_stop(); return action_report(observer, ActionOutcome::completed); }\n    if (mrota::ota_start(out)) {',2,1),
 ('C11 startup sink escapes','src/device_ota.cpp',
  'out.print(F("OTA: SoftAP \'MeshRoute-OTA\' IP="));',
  'mrcon.print(F("OTA: SoftAP \'MeshRoute-OTA\' IP="));',2,1),
 ('C12 startup failure reported successful','src/device_ota.cpp',
  'out.println(F("OTA: SoftAP start FAILED"));\n        return false;',
  'out.println(F("OTA: SoftAP start FAILED"));\n        return true;',2,1),
 ('C13 OTA reset hook omitted','src/fw_main.cpp',
  'mrota::set_pre_reboot_hook([] { mrfault::mark_expected_reset(); });',
  '// missing OTA reset hook',2,1),
 ('C14 wrong nRF reset backend','src/fw_main.cpp',
  'support.reboot = ActionBackend::nrf_reset;','support.reboot = ActionBackend::none;',1,1),
 ('C15 disabled power saving advertised','src/fw_main.cpp',
  '#if !defined(MR_NO_POWERSAVE)\n    support.power_save = true;',
  '#if 1\n    support.power_save = true;',2,0),
 ('C16 real hang loop removed','src/fw_main.cpp',
  'for (;;) { /* no WDT feed -> DOG reset (nRF52); on a no-WDT build this hangs until power-cycle) */ }',
  'return action_report(observer, ActionOutcome::unexpected_return);',2,1),
 ('C17 NV erase moved before inbox warning','src/firmware_commands.cpp',
  'if (!dm_ok || !ch_ok) out.println(F("> factory_reset WARN: inbox erase incomplete (messages may remain on flash)"));\n    const bool nv_ok = mrnv::factory_erase();',
  'const bool nv_ok = mrnv::factory_erase();\n    if (!dm_ok || !ch_ok) out.println(F("> factory_reset WARN: inbox erase incomplete (messages may remain on flash)"));',2,1),
 ('C18 crash flush removed','src/fw_main.cpp',
  'out.println(F("> crashtest reboot — NVIC_SystemReset (SREQ)")); out.flush();',
  'out.println(F("> crashtest reboot — NVIC_SystemReset (SREQ)"));',2,1),
 ('C19 learned-state clear omitted','src/fw_main.cpp',
  '    g_node.clear_learned_state();', '    /* learned-state clear omitted */',2,1),
]
