"""One-source controls; each must compile and fail the executed action assertions."""
CONTROLS = [
 ('C01 second inbox wipe skipped','src/firmware_commands.cpp',
  'const bool dm_ok = g_inbox_dm.wipe(), ch_ok = g_inbox_ch.wipe();',
  'const bool dm_ok = g_inbox_dm.wipe(), ch_ok = true;',2,1),
 ('C02 NV erase skipped','src/firmware_commands.cpp',
  'const bool nv_ok = mrnv::factory_erase();','const bool nv_ok = true;',2,1),
 ('C03 inbox warning suppressed','src/firmware_commands.cpp',
  'if (!dm_ok || !ch_ok) out.println(F("> factory_reset WARN: inbox erase incomplete (messages may remain on flash)"));',
  'if (false) out.println(F("> factory_reset WARN: inbox erase incomplete (messages may remain on flash)"));',2,1),
 ('C04 local confirmation bypassed','src/firmware_commands.cpp',
  'if (admission.status != ActionAdmissionStatus::confirmation) {','if (true) {',2,1),
 ('C05 sleep selection ignored','src/firmware_commands.cpp',
  'action_sleep_apply(admission.plan.kind, out);','action_sleep_apply(ActionKind::sleep_on, out);',2,1),
 ('C06 factory reset sink escapes','src/firmware_commands.cpp',
  'return action_reboot_apply(backend, reboot_out, observer, reset_outcome);',
  'return action_reboot_apply(backend, mrcon, observer, reset_outcome);',2,1),
 ('C07 reset mark missing','src/fw_main.cpp',
  'mrfault::mark_expected_reset();   // v2 fault log: classify the upcoming reset as REBOOT, not UNEXPECTED',
  '// missing expected-reset mark',1,1),
 ('C08 prep does not halt','src/fw_main.cpp',
  'g_halted = true;                              // the loop now skips the operating block',
  'g_halted = false;                             // the loop now skips the operating block',2,1),
 ('C09 apply repeats mutable debug admission','src/fw_main.cpp',
  '    if (plan.kind == ActionKind::crash_hang) {',
  '    if (!meshroute::g_mr_trace_on) return action_report(observer, ActionOutcome::backend_failed);\n    if (plan.kind == ActionKind::crash_hang) {',2,1),
 ('C10 remote entry toggles active OTA off','src/fw_main.cpp',
  '    if (mrota::ota_start(out)) {',
  '    if (mrota::ota_active()) { mrota::ota_stop(); return action_report(observer, ActionOutcome::completed); }\n    if (mrota::ota_start(out)) {',2,1),
 ('C11 startup sink escapes','src/device_ota.cpp',
  'out.print(F("OTA: SoftAP \'MeshRoute-OTA\' IP="));',
  'mrcon.print(F("OTA: SoftAP \'MeshRoute-OTA\' IP="));',2,1),
 ('C12 startup failure reported successful','src/device_ota.cpp',
  'out.println(F("OTA: SoftAP start FAILED"));\n        return false;',
  'out.println(F("OTA: SoftAP start FAILED"));\n        return true;',2,1),
 ('C13 OTA reset hook omitted','src/fw_main.cpp',
  'mrota::set_pre_reboot_hook([] { mrfault::mark_expected_reset(); });',
  '// missing OTA reset hook',2,1),
 ('C14 wrong nRF reset backend','src/fw_main.cpp',
  'support.reboot = ActionBackend::nrf_reset;','support.reboot = ActionBackend::none;',1,1),
 ('C15 disabled power saving advertised','src/fw_main.cpp',
  '#if !defined(MR_NO_POWERSAVE)\n    support.power_save = true;',
  '#if 1\n    support.power_save = true;',2,0),
 ('C16 real hang loop removed','src/fw_main.cpp',
  'for (;;) { /* no WDT feed -> DOG reset (nRF52); on a no-WDT build this hangs until power-cycle) */ }',
  'return action_report(observer, ActionOutcome::unexpected_return);',2,1),
 ('C17 NV erase moved before inbox warning','src/firmware_commands.cpp',
  'if (!dm_ok || !ch_ok) out.println(F("> factory_reset WARN: inbox erase incomplete (messages may remain on flash)"));\n    const bool nv_ok = mrnv::factory_erase();',
  'const bool nv_ok = mrnv::factory_erase();\n    if (!dm_ok || !ch_ok) out.println(F("> factory_reset WARN: inbox erase incomplete (messages may remain on flash)"));',2,1),
 ('C18 crash flush removed','src/fw_main.cpp',
  'out.println(F("> crashtest reboot — NVIC_SystemReset (SREQ)")); out.flush();',
  'out.println(F("> crashtest reboot — NVIC_SystemReset (SREQ)"));',2,1),
 ('C19 learned-state clear omitted','src/fw_main.cpp',
  '    g_node.clear_learned_state();', '    /* learned-state clear omitted */',2,1),
]

# 7b-3 additions. The first 19 P1 controls above remain separate and retain their original pins.
REMOTE_CONTROLS = [
 ('R01 public reboot bypasses preparation','src/firmware_commands.cpp',
  'if (radmin_disruptive_request(policy, ctx)) {',
  'if (radmin_disruptive_request(policy, ctx) && std::string_view(line, len) != "reboot") {',2,1),
 ('R02 OTA bypasses authority','src/firmware_commands.cpp',
  'if (!policy || !command_authority_admits(*policy, ctx, line, len)) {',
  'if ((!policy || !command_authority_admits(*policy, ctx, line, len)) && std::string_view(line, len) != "ota") {',2,1),
 ('R03 typed busy flag lost','src/firmware_commands.cpp',
  'r.action_busy = terminal == meshroute::RemoteTerminal::action_busy;', 'r.action_busy = false;',2,1),
 ('R04 scheduled mapped to completed','src/firmware_commands.cpp',
  'if (terminal == meshroute::RemoteTerminal::scheduled) r.outcome = DispatchOutcome::scheduled;',
  'if (terminal == meshroute::RemoteTerminal::scheduled) r.outcome = DispatchOutcome::completed;',2,1),
 ('R05 admission failure ignored','src/firmware_remote_actions.cpp',
  'if (admission.status != ActionAdmissionStatus::ready) return RemoteTerminal::refused;',
  'if (false) return RemoteTerminal::refused;',2,1),
 ('R06 derived default replaced by fixed delay','src/firmware_remote_actions.cpp',
  'delay.effective_ms);\n    if (result', '299999);\n    if (result',2,1),
 ('R07 invalid live timing accepted','src/firmware_remote_actions.cpp',
  'if (delay.state != ActivationState::default_derived && delay.state != ActivationState::configured)',
  'if (false)',2,1),
 ('R08 wrong OTA output backend label','src/firmware_remote_actions.cpp',
  'admission.plan.backend == ActionBackend::wifi_ota ? F("> ota backend=wifi\\n")',
  'admission.plan.backend == ActionBackend::nrf_dfu ? F("> ota backend=wifi\\n")',2,1),
 ('R09 due consumer never applies','src/firmware_remote_actions.cpp',
  'if (!g_node.radmin_take_action(action)) return;',
  'if (g_node.radmin_take_action(action)) return;',2,1),
 ('R10 sleep apply mode overwritten','src/firmware_remote_actions.cpp',
  'action_sleep_apply(plan.kind, sink, observer);','action_sleep_apply(ActionKind::sleep_on, sink, observer);',2,1),
 ('R11 remote OTA calls local toggle','src/firmware_commands.cpp',
  'if (radmin_disruptive_request(policy, ctx)) {',
  'if (radmin_disruptive_request(policy, ctx) && std::string_view(line, len) != "ota") {',2,1),
 ('R12 typed observer disconnected','src/firmware_remote_actions.cpp',
  'const ActionObserver observer{&report, ActivationReport::report};','const ActionObserver observer{};',2,1),
 ('R13 diagnostic outcome dropped','src/firmware_remote_actions.cpp',
  'g_node.radmin_action_result(self.kind, byte);','g_node.radmin_action_result(self.kind, 0);',2,1),
 ('R14 diagnostic kind dropped','src/firmware_remote_actions.cpp',
  'g_node.radmin_action_result(self.kind, byte);',
  'g_node.radmin_action_result(0, byte);',2,1),
 ('R15 buffer sink forwards raw effect text','src/firmware_remote_actions.cpp',
  'size_t write(const uint8_t*, size_t n) override { return n; }',
  'size_t write(const uint8_t* p, size_t n) override { return mrcon.write(p,n); }',2,1),
 ('R16 transfer not wiped before effect','src/firmware_remote_actions.cpp',
  'crypto_wipe(&action, sizeof action);','/* transfer wipe omitted */',2,1),
 ('R17 ACK trigger diagnostic lies','src/firmware_remote_actions.cpp',
  'trigger == meshroute::RemoteActionTrigger::ack ? "ack" : "deadline"',
  'trigger == meshroute::RemoteActionTrigger::ack ? "deadline" : "ack"',2,1),
 ('R18 status hides early-ACK due ownership','src/firmware_remote_actions.cpp',
  's.phase == RemoteActionPhase::armed || s.phase == RemoteActionPhase::due',
  's.phase == RemoteActionPhase::armed',2,1),
 ('R19 zero request ID hidden','src/firmware_remote_actions.cpp',
  'if (s.phase != RemoteActionPhase::none) {','if (s.request_id != 0) {',2,1),
 ('R20 prepared status wrongly has countdown','src/firmware_remote_actions.cpp',
  'if (armed) decimal64(out, s.remaining_ms); else out.print(F("unarmed"));',
  'decimal64(out, s.remaining_ms);',2,1),
 ('R21 configured delay binding replaced by default','src/firmware_commands.cpp',
  'remote_action_prepare(line, len, *policy, ctx, g_remote_action_activation_ms, stream)',
  'remote_action_prepare(line, len, *policy, ctx, 0, stream)',2,1),
]
